In [63]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [64]:
cal = A.sum(axis=0)
# sum vertically
cal

array([ 59. , 239. , 155.4,  76.9])

In [65]:
percentage = (A*100)/cal
# so this is called broadcasting in python
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [66]:
a = np.random.rand(5)
a

array([0.21034761, 0.48457057, 0.73871202, 0.62769212, 0.68770825])

In [67]:
a.shape
# this shape can have weird behaviour such as transpose of a is a itself and product with transpose is a nmber rather than a matrix

# this does not behave as a column vector or row vector so weird behaviour
# rank 1 array these are called

(5,)

In [69]:
a.T
# due to weird shape of the a its transpose is not made correctly

array([0.21034761, 0.48457057, 0.73871202, 0.62769212, 0.68770825])

In [70]:
np.dot(a,a.T)

1.691690245002803

In [71]:
a = np.random.randn(5,1)
a

array([[ 1.15939479],
       [-1.20785098],
       [-1.12665098],
       [-0.21022607],
       [-1.26837887]])

In [72]:
a.shape

(5, 1)

In [73]:
a.T

array([[ 1.15939479, -1.20785098, -1.12665098, -0.21022607, -1.26837887]])

In [74]:
np.dot(a,a.T)

array([[ 1.34419629, -1.40037614, -1.30623329, -0.24373501, -1.47055186],
       [-1.40037614,  1.45890399,  1.3608265 ,  0.25392176,  1.53201266],
       [-1.30623329,  1.3608265 ,  1.26934244,  0.2368514 ,  1.4290203 ],
       [-0.24373501,  0.25392176,  0.2368514 ,  0.044195  ,  0.2666463 ],
       [-1.47055186,  1.53201266,  1.4290203 ,  0.2666463 ,  1.60878495]])