In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [14]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.975

In [15]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9972222222222222

In [16]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9888888888888889

In [17]:
# the problem with above method is that the score changes with change in random state of train test split
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [19]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)
    # three folds generation

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [20]:
# we dont need to do this all custom as their is an in built python library called cross val score
from sklearn.model_selection import cross_val_score

In [26]:
import warnings
warnings.filterwarnings('ignore')
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [27]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [28]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93333333, 0.90555556, 0.9637883 , 0.96657382, 0.92479109])